#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Oct 10, 2022 02:05:27 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import OVEN_support
bck_colour = "grey"

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = bck_colour  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = bck_colour # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = bck_colour 
        _tabfg2 = bck_colour 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("1415x794")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("Second Display")
        top.configure(background="#555555")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.can60 = tk.Canvas(self.top)
        self.can60.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.can60.configure(background=bck_colour)
        self.can60.configure(borderwidth="2")
        self.can60.configure(highlightbackground="#000000")
        self.can60.configure(highlightcolor="black")
        self.can60.configure(insertbackground=bck_colour)
        self.can60.configure(relief="ridge")
        self.can60.configure(selectbackground="#000000")
        self.can60.configure(selectforeground=bck_colour)

        self.darkmode_button = tk.Button(self.can60,text="Dark mode",command = OVEN_support.dark_mode)
        self.darkmode_button.place(relx=0.1, rely=0.95, height=24, width=100)

        self.lightmode_button = tk.Button(self.can60,text="Light mode",command = OVEN_support.light_mode)
        self.lightmode_button.place(relx=0.02, rely=0.95, height=24, width=100)

def start_up():
    OVEN_support.main()

if __name__ == '__main__':
    OVEN_support.main()




